### ISSUE TITLE
user story #1

### ISSUE THREAD

**Issue by JohannaHopp** [JohannaHopp/personal-website#4]
## Value Proposition

**As a** user
**I need** landing page 
**to be able to** get to know the person introducing him/herself and to get a first impression.

## Description

![Image](https://github.com/JohannaHopp/personal-website/assets/112806881/d944f147-7147-4533-ac3b-a7782489c20a)

## Acceptance Criteria

- [ ] Landingpage wird angezeigt
- [ ] Texte und Fotos sollen korrekt dargestellt werden
- [ ] Farbfelder sind an der korrekten stelle
- [ ] The display is adapted to the end device (monitor, mobile phone, etc.)

## Tasks

- [ ] Create a basic framework
> - [ ] Header
> - [ ] Body
- [ ] Display header in a different colour
- [ ] Display photos in the correct size
- [ ] Display text correctly
